FROM node:20-slim
WORKDIR /usr/src/app
COPY probot/package.json probot/package-lock.json ./
RUN npm ci --production
RUN npm cache clean --force
ENV NODE_ENV=production
COPY probot .
CMD ["npm", "start"]
